name: Deploy (self-hosted)
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted]
    steps:
      - name: Run server script
        run: /root/rebuild-site.sh
