name: Deploy (self-hosted)
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted]
    steps:
      - name: Run server script
        run: /root/rebuild-site.sh
